version: "3"
services:
  controller:
    image: vc-authn-oidc-controller
    entrypoint: bash -c "alembic upgrade head && uvicorn api.main:app --reload --host 0.0.0.0 --port 5000 --log-level info"
    depends_on:
      controller-db:
        condition: service_healthy
      controller-ngrok:
        condition: service_started
    environment:
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
      - POSTGRESQL_DB=${POSTGRESQL_DB}
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - ACAPY_ADMIN_URL=${ACAPY_ADMIN_URL}
      - ACAPY_TENANCY=${ACAPY_TENANCY}
      - MT_ACAPY_WALLET_ID=${MT_ACAPY_WALLET_ID}
      - MT_ACAPY_WALLET_KEY=${MT_ACAPY_WALLET_KEY}
      - ST_ACAPY_ADMIN_API_KEY=${ST_ACAPY_ADMIN_API_KEY}
      - ST_ACAPY_ADMIN_API_KEY_NAME=${ST_ACAPY_ADMIN_API_KEY_NAME}
      - ACAPY_NGROK_TUNNEL_HOST=${ACAPY_NGROK_TUNNEL_HOST}
      - CONTROLLER_NGROK=${CONTROLLER_NGROK}
    ports:
      - ${CONTROLLER_SERVICE_PORT}:5000
    volumes:
      - ../oidc-controller:/app:rw
    networks:
      - vc_auth

  controller-db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - controller-db-data:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/1-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - vc_auth

  keycloak:
    image: jboss/keycloak:16.0.0
    ports:
      - 8880:8080
    volumes:
      - ./keycloak/config:/tmp
    environment:
      DB_VENDOR: ${KEYCLOAK_DB_VENDOR}
      DB_ADDR: ${KEYCLOAK_DB_ADDR}
      DB_DATABASE: ${KEYCLOAK_DB_NAME}
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_LOGLEVEL: ${KEYCLOAK_LOGLEVEL}
      ROOT_LOGLEVEL: ${KEYCLOAK_ROOT_LOGLEVEL}
      KEYCLOAK_IMPORT: ${KEYCLOAK_IMPORT}
    depends_on:
      - keycloak-db
    networks:
      - vc_auth

  keycloak-db:
    image: registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest
    environment:
      POSTGRESQL_USER: ${KEYCLOAK_DB_USER}
      POSTGRESQL_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      POSTGRESQL_DATABASE: ${KEYCLOAK_DB_NAME}
    volumes:
      - keycloak-db-data:/var/lib/pgsql/data
    networks:
      - vc_auth

  controller-ngrok:
    image: wernight/ngrok
    environment:
      - CONTROLLER_SERVICE_PORT=5000
    ports:
      - 4056:4040
    command: ngrok http controller:5000 --log stdout
    networks:
      - vc_auth
  
  aca-py-ngrok:
    image: wernight/ngrok
    environment:
      - AGENT_HTTP_PORT=${AGENT_HTTP_PORT}
    ports:
      - 4059:4040
    command: ngrok http aca-py:${AGENT_HTTP_PORT} --log stdout
    networks:
      - vc_auth

  aca-py:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.5
    environment:
      - ACAPY_LABEL=${AGENT_NAME}
      - ACAPY_ENDPOINT=${AGENT_ENDPOINT}
      - ACAPY_GENESIS_URL=${GENESIS_URL}
      - ACAPY_WALLET_NAME=oidc_agent_wallet
      - ACAPY_WALLET_TYPE=indy
      - ACAPY_WALLET_KEY=${WALLET_ENCRYPTION_KEY}
      - ACAPY_WALLET_SEED=${AGENT_SEED}
      - ACAPY_AUTO_VERIFY_PRESENTATION=true
      - ACAPY_WALLET_STORAGE_TYPE=${WALLET_TYPE}
      - ACAPY_LOG_LEVEL=debug
      - ACAPY_WEBHOOK_URL=${CONTROLLER_WEB_HOOK_URL}
      - ACAPY_AUTO_PROVISION=true
      - POSTGRESQL_WALLET_HOST=${POSTGRESQL_WALLET_HOST}
      - POSTGRESQL_WALLET_PORT=${POSTGRESQL_WALLET_PORT}
      - POSTGRESQL_WALLET_USER=${POSTGRESQL_USER}
      - POSTGRESQL_WALLET_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_WALLET_ADMIN_PASSWORD=${POSTGRESQL_ADMIN_PASSWORD}
      - POSTGRESQL_WALLET_ADMIN_USER=${POSTGRESQL_WALLET_ADMIN_USER}
    ports:
      - ${AGENT_ADMIN_PORT}:${AGENT_ADMIN_PORT}
      - ${AGENT_HTTP_PORT}:${AGENT_HTTP_PORT}
    networks:
      - vc_auth
    depends_on:
      - wallet-db
      - aca-py-ngrok
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 14;
        aca-py start \
        --inbound-transport http '0.0.0.0' ${AGENT_HTTP_PORT} \
        --outbound-transport http \
        --wallet-storage-config '{\"url\":\"${POSTGRESQL_WALLET_HOST}:${POSTGRESQL_WALLET_PORT}\",\"max_connections\":5}' \
        --wallet-storage-creds '{\"account\":\"${POSTGRESQL_WALLET_USER}\",\"password\":\"${POSTGRESQL_WALLET_PASSWORD}\",\"admin_account\":\"${POSTGRESQL_WALLET_ADMIN_USER}\",\"admin_password\":\"${POSTGRESQL_WALLET_ADMIN_PASSWORD}\"}' \ 
        --admin '0.0.0.0' ${AGENT_ADMIN_PORT} \
        --${ACAPY_ADMIN_MODE} 
      "
      ]

  wallet-db:
    image: registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest
    environment:
      - POSTGRESQL_USER=${POSTGRESQL_WALLET_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_WALLET_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_WALLET_DATABASE}
      - POSTGRESQL_ADMIN_PASSWORD=${POSTGRESQL_WALLET_ADMIN_PASSWORD}
    networks:
      - vc_auth
    ports:
      - 5433:5432
    volumes:
      - agent-wallet-db:/var/lib/pgsql/data


networks:
  vc_auth:
    driver: bridge


volumes:
  controller-db-data:
  keycloak-db-data:
  agent-wallet-db:
  
