name: Build & Deploy Development
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: "Build VC-AuthN"
    if: github.repository_owner == 'bcgov'
    uses: ./.github/workflows/publish.yml
    with:
      tag: "dev"
      ref: "main"
      platforms: "linux/amd64"

  # Build vc-authn
  deploy:
    name: Deploy VC-AuthN to Dev
    environment: dev
    runs-on: ubuntu-latest
    needs:
      - build
    if: ${{ always() && !(contains(needs.*.result, 'failed')) && (github.repository_owner == 'bcgov') }}

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: VC-Authn Dev Helm
        run: |
          helm upgrade --install vc-authn-oidc \
          -f https://raw.githubusercontent.com/bcgov/trust-over-ip-configurations/main/helm-values/vc-authn-oidc/dev.yaml \
          --set image.tag="dev" \
          ./charts/vc-authn-oidc --wait
      - name: Restart Deployments
        run: |
          oc rollout restart deployment/vc-authn-oidc-agent
          oc rollout restart deployment/vc-authn-oidc
