name: Publish VC-AuthN Image

env:
  IMAGE_NAME: vc-auth-2060

on:
  push:
    branches: [main, dev]

jobs:
  publish_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/oidc-controller/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_LOGIN }}/${{ env.IMAGE_NAME }}:${{ steps.extract.outputs.branch }}
